---
- hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - name: Schedule a task with at command
      at: 
        units: minutes #hours, weeks, months, days
        count: 20
        command: "yum install httpd -y" 
 
