---
- hosts: all
  tasks:
    - name: Chose Centos 7 only
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      file:
        path: /tmp/shaka
        state: touch
