---
- hosts: all 
  become: yes
  become_method: sudo 
  connection: ssh
  tasks:
    - name: Copying test file to remote system 
      copy:
        src:  /etc/passwd
        dest:  /mnt/list_of_users
        remote_src: yes
