--- #This is Farkhod's playbook
- hosts: all
  tasks:
    - name: Install apache on Centos 6
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      yum: name=httpd     state=latest

    - name: Copy file to index.html
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      copy:
        dest: /var/www/html/index.html
        content: "Hello world"

    - name: Start apache on CentOS 7 
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      systemd:
        name: httpd
        state: restarted

    - name: Install firewalld on CentOS 7
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      yum:
        name: firewalld
        state: installed

    - name: Run firewalld on CentOS 7 
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      systemd:
        name: firewalld
        state: restarted
        enabled: yes

    - name: Add rule to firewalld    
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      firewalld:
        service: httpd
        permanent: true
        state: enabled

    - name: add ssh rule             
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
      firewalld:
        service: sshd
        permanent: true
        state: enabled
##############################


    - name: Install mysql on ubuntu 
      when: (ansible_distribution == "Debian")
      package:
        name: "{{ item }}"
        state: latest
      with_item:
        - php
        - mysql-server
      notify: MYSQL

    - name: Ryn mysql
      systemd:
        name: mysqld
        state: restarted

