---
- hosts: all
  become: yes
  become_method: sudo 
  tasks: 
    - package: name=httpd state=installed

    - name: Sleep for 1 minute
      pause:
        seconds: 15

    - name: 
      package: name=httpd state=removed
